package taskDB;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.os.Parcel;
import android.os.Parcelable;

import java.util.Date;
// KEEP INCLUDES END
/**
 * Entity mapped to table TASK.
 */
public class Task implements Parcelable{

    /** Not-null value. */
    private String id;
    /** Not-null value. */
    private String title;
    /** Not-null value. */
    private String description;
    /** Not-null value. */
    private java.util.Date startDate;
    /** Not-null value. */
    private java.util.Date finishDate;
    /** Not-null value. */
    private java.util.Date createdOn;
    /** Not-null value. */
    private java.util.Date modifiedOn;
    private transient boolean syncronized;
    private transient boolean newTask;

    // KEEP FIELDS - put your custom fields here
    public static final Parcelable.Creator<Task> CREATOR = new Parcelable.Creator<Task>() {
        @Override
        public Task createFromParcel(Parcel source) {
            return new Task(source);
        }

        @Override
        public Task[] newArray(int size) {
            return new Task[size];
        }
    };
    // KEEP FIELDS END

    public Task() {
        newTask = false;
        syncronized = true;
    }

    public Task(String id) {
        this.id = id;
        newTask = true;
    }

    public Task(String id, String title, String description, java.util.Date startDate, java.util.Date finishDate, java.util.Date createdOn, java.util.Date modifiedOn, Boolean syncronized, Boolean newTask) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.startDate = startDate;
        this.finishDate = finishDate;
        this.createdOn = createdOn;
        this.modifiedOn = modifiedOn;
        this.syncronized = syncronized;
        this.newTask = newTask;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    /** Not-null value. */
    public String getDescription() {
        return description;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescription(String description) {
        this.description = description;
    }

    /** Not-null value. */
    public java.util.Date getStartDate() {
        return startDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStartDate(java.util.Date startDate) {
        this.startDate = startDate;
    }

    /** Not-null value. */
    public java.util.Date getFinishDate() {
        return finishDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFinishDate(java.util.Date finishDate) {
        this.finishDate = finishDate;
    }

    /** Not-null value. */
    public java.util.Date getCreatedOn() {
        return createdOn;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedOn(java.util.Date createdOn) {
        this.createdOn = createdOn;
    }

    /** Not-null value. */
    public java.util.Date getModifiedOn() {
        return modifiedOn;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setModifiedOn(java.util.Date modifiedOn) {
        this.modifiedOn = modifiedOn;
    }

    public Boolean getSyncronized() {
        return syncronized;
    }

    public void setSyncronized(Boolean syncronized) {
        this.syncronized = syncronized;
    }

    public Boolean getNewTask() {
        return newTask;
    }

    public void setNewTask(Boolean newTask) {
        this.newTask = newTask;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(id);
        dest.writeString(title);
        dest.writeString(description);
        dest.writeValue(startDate);
        dest.writeValue(finishDate);
        dest.writeValue(createdOn);
        dest.writeValue(modifiedOn);
        dest.writeValue(syncronized);
        dest.writeValue(newTask);
    }

    @Override
    public String toString() {
        return "Task{" +
                "id='" + id + '\'' +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", startDate=" + startDate +
                ", finishDate=" + finishDate +
                ", createdOn=" + createdOn +
                ", modifiedOn=" + modifiedOn +
                ", syncronized=" + syncronized +
                ", newTask=" + newTask +
                '}';
    }

    public Task(Parcel source) {
        this.id = source.readString();
        this.title = source.readString();
        this.description = source.readString();
        this.startDate = (java.util.Date) source.readValue(java.util.Date.class.getClassLoader());
        this.finishDate = (java.util.Date) source.readValue(java.util.Date.class.getClassLoader());
        this.createdOn = (Date) source.readValue(Date.class.getClassLoader());
        this.modifiedOn = (Date) source.readValue(Date.class.getClassLoader());
        this.syncronized = (Boolean) source.readValue(java.lang.Boolean.class.getClassLoader());
        this.newTask = (Boolean) source.readValue(java.lang.Boolean.class.getClassLoader());
    }
    // KEEP METHODS END

}
